global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'blogit-dev'
    replica: 'prometheus-01'

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'alloy'
    static_configs:
      - targets: ['alloy:12345']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'user-service'
    metrics_path: '/api/v1/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['user-service:8081']

  - job_name: 'post-service'
    metrics_path: '/api/v1/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['post-service:8082']

  - job_name: 'interaction-service'
    metrics_path: '/api/v1/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['interaction-service:8083']


